services:
  app:
    build:
      context: .
      target: development
    container_name: menyalka_server
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development
    depends_on:
      - postgres
      - pgadmin
  postgres:
    image: postgres:16.4
    container_name: postgres-dev
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-menyalka_dev}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-changeme}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    restart: unless-stopped
    depends_on:
      - postgres
  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env.development
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
volumes:
  pgdata:
  pgadmin:
  redis:
