export const AUTH_SERVICE_OPTIONS = Symbol('AUTH_SERVICE_OPTIONS');
export const AUTH_SERVICE = Symbol('AUTH_SERVICE');
export const TELEGRAM_OAUTH_SERVICE = Symbol('TELEGRAM_OAUTH_SERVICE');
export const OAUTH_FACTORY_SERIVCE = Symbol('OAUTH_FACTORY_SERIVCE');
