export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const PERMISSION_REPOSITORY = Symbol('PERMISSION_REPOSITORY');
export const ACCESS_CONTROL_SERVICE = Symbol('ACCESS_CONTROL_SERVICE');
