export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_SOCIAL_CREDENTIALS_REPOSITORY = 'USER_SOCIAL_CREDENTIALS_REPOSITORY';
export const USER_SERVICE = 'USER_SERVICE';
export const USER_SERVICE_OPTIONS = 'USER_SERVICE_OPTIONS';
