export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const USER_SOCIAL_CREDENTIALS_REPOSITORY = Symbol('USER_SOCIAL_CREDENTIALS_REPOSITORY');
export const USER_SERVICE = Symbol('USER_SERVICE');
export const USER_SERVICE_OPTIONS = Symbol('USER_SERVICE_OPTIONS');
